# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    name: ubuntu-latest (release)

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2-branch
        with:
          r-version: 'release'

      - uses: r-lib/actions/setup-pandoc@v2-branch

      - uses: r-lib/actions/setup-tinytex@v2-branch

      - uses: r-lib/actions/setup-r-dependencies@v2-branch
        with:
          extra-packages: any::rcmdcheck, any::tinytex
          needs: check

      - name: Install additional LaTeX packages
        run: |
          tinytex::tlmgr_install(c(
            "mathpazo",
            "booktabs",
            "rotating",
            "makecell",
            "pdfpages",
            "pifont",
            "academicons",
            "fontawesome"
          ))
        shell: Rscript {0}
        
      - name: Check
        env:
          _R_CHECK_CRAN_INCOMING_REMOTE_: false
        run: rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"), error_on = "error", check_dir = "check")
        shell: Rscript {0}

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@main
        with:
          name: R-CMD-check-results
          path: check
